---
title: "Trials for reproducing Montano-Centellas et al. (2020)"
author: Karthik Thrikkadeeri
toc: true
number-sections: false
embed-resources: true
bibliography: ../PhD.json
theme: sandstone
format: html
execute:
  warning: false
editor_options: 
  chunk_output_type: console
---

```{r}
library(dplyr)
library(readxl) # file is .xlsx
library(glue)
library(ggplot2); theme_set(theme_classic())
library(purrr)

data_dryad <- read_xlsx("data/montano_dryad_data.xlsx",
                        sheet = "FDPD_Supporting")

```

## What are the diversity patterns? (Quadratic regressions)

### Fitting the models

The polynomial model is fit to each mountain separately, so need to iterate.

```{r}

# iterate over each mountain in the dataset:
# fit LM of FRic against linear and second-order polynomial terms of Elevation
# extract intercept and coefficients for both Elevation terms
# aggregate all these values over all mountains

map(unique(data_dryad$Mountain), ~ {
  
  data_mount <- data_dryad %>% filter(Mountain == .x)
  
  model_mount <- lm(FRic ~ elevation + I(elevation^2), data_mount)
  model_mount_summary <- summary(model_mount)
  
  t(model_mount$coefficients) %>% 
    as_tibble() %>% 
    magrittr::set_colnames(c("Intercept", "Elevation", "Elevation2")) %>% 
    bind_cols(tibble(Mountain = .x))
  
}) %>% 
  list_rbind()



```

